import { createElement } from 'lwc';
import ALL_LWC_TASK from 'c/aLL_LWC_TASK';

describe('c-a-l-l-l-w-c-task', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a-l-l-l-w-c-task', {
            is: ALL_LWC_TASK
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});