public class All_Task {
    public All_Task() {
    }
 
    public PageReference Task_1(){
        return Page.StandardContact;
    }
    public PageReference Task_2(){
        return Page.Task_2;
    }
    public PageReference Task_3(){
        return Page.Task_3;
    }
    public PageReference Task_4(){
        return Page.Task_4;
    }
    public PageReference Task_5(){
        return Page.Task_5;
    }
    public PageReference Task_6(){
        return Page.Task_6;
    }
    public PageReference Task_3_additional(){
        return Page.task_3_changes;
    }
}
